run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/subnetmarco/ssepg
  funlen:
    lines: 100
    statements: 50
  gosec:
    excludes:
      - G404 # Use of weak random number generator - not relevant for this use case

linters:
  disable-all: true
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Code quality
    - dupl
    - gocyclo
    - goconst
    - funlen
    - misspell
    - unconvert
    - unparam
    
    # Style and formatting
    - gofmt
    - goimports
    - whitespace
    
    # Security
    - gosec

issues:
  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
        - gosec
    
    # Exclude long lines in generated code or specific patterns
    - linters:
        - lll
      source: "^//go:generate "

  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0